### ISSUE TITLE
Include assets

### ISSUE THREAD

**Issue by ghost** [zeinash/prj-rev-bwfs-dasmoto#3]
https://github.com/zeinash/prj-rev-bwfs-dasmoto/blob/master/06_dasmotos/index.html#L18

Consider including your website's assets (in this case images) in your project and provide a relative file path to them in your `img` tags. 

It's always better to provide static assets up front instead of depending on external URLs that could fail or otherwise become unavailable.

**Comment by zeinash** [comment]
Yes, I wasn't sure on which route to go, thank you for the clarification!
