### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [zeinash/prj-rev-bwfs-dasmoto#6]
https://github.com/zeinash/prj-rev-bwfs-dasmoto/blob/master/06_dasmotos/resources/css/style.css#L1-L17

Excellent job keeping your CSS organized and easy to read, and moving shared/common styles into more general selectors to avoid repetition 👍

**Comment by zeinash** [comment]
This was worrying me the most, I'm glad I got it right! 😄
