### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [zeinash/prj-rev-bwfs-dasmoto#7]
Exceeds Expectations 🚀 

You've successfully reproduced the website according to the design mock. You've demonstrated a solid understanding of using HTML to markup your page's content and structure and of using CSS to apply fundamental styles.

Great work using a semantic tag like `section` and keeping your CSS so efficient! 👍

**Comment by zeinash** [comment]
I am so happy to hear this! Thank you very much for your time and detailed review. I went over everything closely 🙏
